title: From Postpedagogy to Design Pedagogy
permalink: pretty
author:
  - last-name: Ceraso
    first-name: Steph
    institution: University of Virginia
  - last-name: Pavesich
    first-name: Matthew
    institution: Georgetown University

